-- +goose Up
-- +goose StatementBegin
CREATE TABLE users (
	id 				int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username		varchar(16) NOT NULL,
	full_name 		text NOT NULL,
	email 			text NOT NULL,
	password 		text NOT NULL,
	profile_image 	text,
	follower_count	int NOT NULL DEFAULT 0,
	following_count int NOT NULL DEFAULT 0,
	created_at 		timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tweets (
	id 			int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content		text NOT NULL,
	like_count 	int NOT NULL DEFAULT 0,
	user_id 	int NOT NULL REFERENCES users(id),
	created_at 	timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_at	timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes (
	id 			int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id		int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	tweet_id	int NOT NULL REFERENCES tweets(id) ON DELETE CASCADE,
	created_at 	timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE follows (
	id				int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	follower_id		int NOT NULL REFERENCES users(id),
	following_id	int NOT NULL REFERENCES users(id),

	CONSTRAINT unique_follow UNIQUE (follower_id, following_id)
);

CREATE TABLE feeds (
	id 			int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tweet_id	int NOT NULL REFERENCES tweets(id) ON DELETE CASCADE,
	user_id		int NOT NULL REFERENCES users(id) ON DELETE CASCADE
)

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS feeds;

DROP TABLE IF EXISTS follows;

DROP TABLE IF EXISTS likes;

DROP TABLE IF EXISTS tweets;

DROP TABLE IF EXISTS users;
-- +goose StatementEnd
