##
## Build
##

FROM golang:1.23.3-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o twitter-clone-backend-bin

##
## Deploy
##

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app ./

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/twitter-clone-backend-bin"]