version: "3.8"

services:
  go-server:
    build: 
      context: .
      dockerfile: Dockerfile.multistage
    depends_on: 
      - postgres # service name
      - redis
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file: .env.dev.docker
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - myvolume:/var/lib/postgresql/data 
    networks:
      - mynet
    env_file: .env.dev.docker
  redis:
    image: redis/redis-stack
    ports:
    - "6379:6379"
    networks:
      - mynet
    env_file: .env.dev.docker

volumes:
  myvolume:

networks:
  mynet:
    driver: bridge