services:
  go-server:
    image: ranjabi/twitter-clone-backend:${DOCKER_TAG}
    pull_policy: always
    depends_on: 
      - postgres
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      ENV_NAME: ${ENV_NAME}
    deploy:
      restart_policy:
          condition: on-failure
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - mynet
  redis:
    image: /data redis/redis-stack:redis/redis-stack-server:7.2.0-v13
    ports:
    volumes:
      - redisdata:/data
    networks:
      - mynet

volumes:
  pdgdata:
  redisdata:

networks:
  mynet:
    driver: bridge