services:
  go-server:
    image: ranjabi/twitter-clone-backend:${DOCKER_TAG}
    pull_policy: always
    depends_on: 
      - postgres
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      ENV_NAME: ${ENV_NAME}
    deploy:
      restart_policy:
          condition: on-failure
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - myvolume:/var/lib/postgresql/data 
    networks:
      - mynet
  redis:
    image: redis/redis-stack
    ports:
    - "6379:6379"
    networks:
      - mynet

volumes:
  myvolume:

networks:
  mynet:
    driver: bridge